### ISSUE TITLE
ncreatescu.py fails with raw DICOM files

### ISSUE THREAD

**Issue by dwikler** [sjswerdloff/tdwii_plus_examples#78]
Some tools may encode the UPS dataset without the DICOM Part 10 file format header or with an incomplete header (missing the 128 byte File Preamble, followed by a 4 byte DICOM prefix).
Using such a file as argument of the ncreatescu.py produces the following error:
E: Bad DICOM file.

**Comment by dwikler** [comment]
This is the expected behavior of the pydicom dcmread function and can be avoided using the force:bool parameter. See [pydicom reference guide - Reading and writing DICOM files](https://pydicom.github.io/pydicom/1.1/ref_guide.html#file-reading-parsing)

**Comment by sjswerdloff** [comment]
Also see:
https://github.com/sjswerdloff/tdwii_plus_examples/blob/main/convert_to_explicit_little_endian.py
For a workaround (that includes addressing private element issues).
